import AppKit
import Foundation

/// Watches the general pasteboard. When a GitHub PR URL or Linear issue URL is
/// copied, it briefly replaces the pasteboard with the bare ticket reference
/// (PR number / issue key) so Maccy records it as a separate history item, and
/// then restores the URL (Maccy dedup-merges it back to the top, and ⌘V keeps
/// pasting the URL).
final class Watcher {
  private let pasteboard = NSPasteboard.general
  private let pollInterval: TimeInterval = 0.25
  /// Maccy's default clipboardCheckInterval is 0.5s; wait longer than that
  /// between pasteboard writes so Maccy records every step.
  private let maccyRecordDelay: TimeInterval = 1.0
  /// Pasteboard markers used by password managers and other apps for
  /// clipboard contents that should not be recorded.
  private let ignoredTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType"
  ]

  private var lastChangeCount: Int

  init() {
    lastChangeCount = pasteboard.changeCount
  }

  func run() -> Never {
    Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [self] _ in
      check()
    }
    RunLoop.main.run()
    exit(0)
  }

  private func check() {
    guard pasteboard.changeCount != lastChangeCount else { return }
    lastChangeCount = pasteboard.changeCount

    let types = pasteboard.types ?? []
    guard !types.contains(where: { ignoredTypes.contains($0.rawValue) }) else { return }

    guard let string = pasteboard.string(forType: .string),
          let reference = extractTicketReference(from: string) else { return }

    let url = string.trimmingCharacters(in: .whitespacesAndNewlines)
    let urlChangeCount = pasteboard.changeCount

    // Step 1: after Maccy has recorded the URL, put the ticket reference on the pasteboard.
    DispatchQueue.main.asyncAfter(deadline: .now() + maccyRecordDelay) { [self] in
      // Abort if something else was copied in the meantime.
      guard pasteboard.changeCount == urlChangeCount else { return }
      write(reference)
      let referenceChangeCount = pasteboard.changeCount

      // Step 2: after Maccy has recorded the reference, restore the URL.
      DispatchQueue.main.asyncAfter(deadline: .now() + maccyRecordDelay) { [self] in
        guard pasteboard.changeCount == referenceChangeCount else { return }
        write(url)
      }
    }
  }

  private func write(_ string: String) {
    pasteboard.clearContents()
    pasteboard.setString(string, forType: .string)
    // Ignore our own writes in the next poll.
    lastChangeCount = pasteboard.changeCount
  }
}
